apiVersion: apps/v1 #versao
kind: Deployment #o tipo
metadata:
  name: hello-app-depoyment 
spec: #especificações
  replicas: 4
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-spring
          image: weslley123/teste-kub:3