---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-app #o mesmo do deployment
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1 #versao
kind: Deployment #o tipo
metadata:
  name: hello-app-depoyment 
spec: #especificações
  replicas: 4
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-spring
          image: weslley123/teste-kub:3