apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-app #o mesmo do deployment
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: LoadBalancer